const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    pathForFile: (file) => webUtils.getPathForFile(file),
    sendPrompt: (text, activeServices, filePaths) => ipcRenderer.send('send-prompt', text, activeServices, filePaths),
    toggleService: (service, isEnabled) => ipcRenderer.send('toggle-service', service, isEnabled),
    onServiceStatusUpdate: (callback) => ipcRenderer.on('service-status-update', (event, data) => callback(data)),
    externalLogin: (service) => ipcRenderer.send('external-login', service),
    newChat: () => ipcRenderer.send('new-chat'),
    newChatForService: (service) => ipcRenderer.send('new-chat-for-service', service),
    reloadService: (service) => ipcRenderer.send('reload-service', service),
    navigateToUrl: (service, url) => ipcRenderer.send('navigate-to-url', service, url),
    copyChatThread: (options) => ipcRenderer.send('copy-chat-thread', options),
    onChatThreadCopied: (callback) => ipcRenderer.on('chat-thread-copied', (event, data) => callback(data)),
    copySingleChatThread: (service, options) => ipcRenderer.send('copy-single-chat-thread', service, options),
    onSingleChatThreadCopied: (callback) => ipcRenderer.on('single-chat-thread-copied', (event, data) => callback(data)),
    copyLastResponse: (options) => ipcRenderer.send('copy-last-response', options),
    onLastResponseCopied: (callback) => ipcRenderer.on('last-response-copied', (event, data) => callback(data)),
    crossCheck: (isAnonymousMode, promptPrefix) => ipcRenderer.send('cross-check', isAnonymousMode, promptPrefix),
    toggleScrollSync: (isEnabled) => ipcRenderer.send('toggle-scroll-sync', isEnabled),
    setLayout: (layout) => ipcRenderer.send('set-layout', layout),
    updateViewBounds: (bounds) => ipcRenderer.send('update-view-bounds', bounds),
    saveTempFile: (buffer, name) => ipcRenderer.invoke('save-temp-file', { buffer, name }),
    onFileUploadComplete: (callback) => ipcRenderer.on('file-upload-complete', () => callback()),
    confirmSend: () => ipcRenderer.send('confirm-send'),
    setServiceVisibility: (isVisible) => ipcRenderer.send('set-service-visibility', isVisible),
    // URL Bar APIs (URLBAR-005)
    openUrlInChrome: (url) => ipcRenderer.send('open-url-in-chrome', url),
    onWebviewUrlChanged: (callback) => ipcRenderer.on('webview-url-changed', (event, data) => callback(data)),
    requestCurrentUrls: () => ipcRenderer.send('request-current-urls'),
    // Session Persistence APIs (SESS)
    onApplySavedState: (callback) => ipcRenderer.on('apply-saved-state', (event, state) => callback(state)),
    reportUiState: (state) => ipcRenderer.send('report-ui-state', state),
    getSavedSession: () => ipcRenderer.invoke('get-saved-session'),
    getCurrentUrls: () => ipcRenderer.invoke('get-current-urls'),
    onAppWillClose: (callback) => ipcRenderer.on('app-will-close', () => callback()),
    appCloseReady: () => ipcRenderer.invoke('app-close-ready'),
    // Auto Update APIs
    checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    installUpdate: () => ipcRenderer.invoke('install-update'),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    onUpdateStatus: (callback) => ipcRenderer.on('update-status', (event, data) => callback(data)),
    // Prompt persistence
    getCustomPrompts: () => ipcRenderer.invoke('get-custom-prompts'),
    saveCustomPrompts: (prompts) => ipcRenderer.invoke('save-custom-prompts', prompts),
    getPredefinedPrompt: () => ipcRenderer.invoke('get-predefined-prompt'),
    savePredefinedPrompt: (promptText) => ipcRenderer.invoke('save-predefined-prompt', promptText),
    // Chat Mode APIs (Single AI / Multi AI)
    setChatMode: (mode, config) => ipcRenderer.invoke('set-chat-mode', mode, config),
    getChatMode: () => ipcRenderer.invoke('get-chat-mode'),
    toggleSingleInstance: (instanceIndex, enabled) => ipcRenderer.send('toggle-single-instance', instanceIndex, enabled),
    onChatModeChanged: (callback) => ipcRenderer.on('chat-mode-changed', (event, data) => callback(data)),
    onSingleInstanceUrlChanged: (callback) => ipcRenderer.on('single-instance-url-changed', (event, data) => callback(data)),
    // Single AI Mode specific
    sendPromptToInstances: (text, instanceKeys, filePaths) => ipcRenderer.send('send-prompt-to-instances', text, instanceKeys, filePaths),
    navigateInstance: (instanceKey, url) => ipcRenderer.send('navigate-instance', instanceKey, url),
    reloadInstance: (instanceKey) => ipcRenderer.send('reload-instance', instanceKey),
    newChatForInstance: (instanceKey) => ipcRenderer.send('new-chat-for-instance', instanceKey),
    updateSingleViewBounds: (bounds) => ipcRenderer.send('update-single-view-bounds', bounds)
});
